version: '3.2'
services:
  postgres:
    restart: always
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: alexandria
      POSTGRES_USER: postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    command: postgres -N 500

  athena:
    restart: always
    build:
      context: ./athena
    ports:
      - "3001:8080"
    depends_on:
      - postgres
      - hermes
    volumes:
      - "${SRC_DIR}/athena/app:/go/src/dylan.com/user/athena/app:delegated"

  migrator:
    restart: always
    build:
      context: ./migrator
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - "${SRC_DIR}/migrator:/app:delegated"
    command: yarn run dev

  hephaestus:
    restart: "no"
    build:
      context: ./hephaestus
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - "${SRC_DIR}/hephaestus:/app:delegated"
    command: yarn run migrate
